Add multi-page image uploads
BloomTech-Labs/story-squad-be-archived pull request #21
Opened 2020-01-31 23:00 UTC by EricBanker12

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-02-03 16:57 UTC, EricBanker12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Child] - Upload multiple images](https://trello.com/c/LVfc6AnV/52-child-upload-multiple-images)

2020-02-03 20:47 UTC, wSedlacek requested changes

2020-02-03 20:47 UTC, wSedlacek commented on src/routes/submissions/submissions.routes.ts
> +            Submissions & Pages
This shouldn't be `Submissions & Pages` `Submissions` already has the `.pages` object, so submissions should be coming on that.

2020-02-03 20:47 UTC, wSedlacek commented on src/routes/submissions/submissions.routes.spec.ts
> +                page5: '',
This does not match the `Submissions` shape. It should be 
```js
{
  storyText: 'Text2',
  illustration: '',
  story: {
    page1: '',
    page2: '',
    page3: '',
    page4: '',
    page5: '',
  }
}
```

2020-02-03 20:47 UTC, wSedlacek commented on src/models/dto/submissions/submission.dto.ts
> +    page5: string;
The `SubmissionDTO` should mirror the Submission Entity

2020-02-03 21:01 UTC, EricBanker12 commented on src/routes/submissions/submissions.routes.spec.ts
> +                page5: '',
Yeah, I did it all in one level because I didn't want to rewrite another file input handler, but it probably would be better to do so.

2020-02-03 21:08 UTC, Forrestdarabian approved these changes
Just minor things to be fixed, all tests are working locally. Great job

2020-02-03 21:08 UTC, Forrestdarabian commented on src/routes/submissions/submissions.routes.spec.ts
> +                page5: '',
Following the same format as Submissions would be more efficient

2020-02-03 21:08 UTC, Forrestdarabian commented on src/routes/submissions/submissions.routes.ts
> +            Submissions & Pages
Remove `& Pages` from line 36

2020-02-04 21:28 UTC, wSedlacek approved these changes
Looks good, has some room for improvement but that can be addressed in future updates

2020-02-04 21:29 UTC, merged